module.exports = {
  plugins: ['jest'],
  env: {
    'jest': true,
  },
  extends: [
    'plugin:jest/recommended',
  ],
  rules: {
    'jest/expect-expect': 1,
    'jest/lowercase-name': 0,
    'jest/no-alias-methods': 1,
    'jest/no-disabled-tests': 1,
    'jest/no-empty-title': 1,
    'jest/no-focused-tests': 1,
    'jest/no-hooks': 1,
    'jest/no-identical-title': 1,
    'jest/no-jasmine-globals': 1,
    'jest/no-jest-import': 1,
    'jest/no-large-snapshots': 1,
    'jest/no-test-callback': 1,
    'jest/no-test-prefixes': 1,
    'jest/no-test-return-statement': 1,
    'jest/no-truthy-falsy': 1,
    'jest/prefer-expect-assertions': 0,
    'jest/prefer-spy-on': 1,
    'jest/prefer-strict-equal': 1,
    'jest/prefer-to-be-null': 1,
    'jest/prefer-to-be-undefined': 1,
    'jest/prefer-to-contain': 1,
    'jest/prefer-to-have-length': 1,
    'jest/prefer-inline-snapshots': 1,
    'jest/require-tothrow-message': 1,
    'jest/valid-describe': 1,
    'jest/valid-expect-in-promise': 1,
    'jest/valid-expect': 1,
    'jest/prefer-todo': 1,
    'jest/prefer-called-with': 1,
  },
};
