module.exports = {
  'plugins': [
    'jest',
  ],
  'env': {
    'jest': true,
  },
  'extends': [
    'plugin:jest/recommended',
  ],
  'rules': {
    'jest/consistent-test-it'           : 'warn',
    'jest/expect-expect'                : 'warn',
    'jest/lowercase-name'               : 'off',
    'jest/max-nested-describe'          : 'warn',
    'jest/no-alias-methods'             : 'warn',
    'jest/no-commented-out-tests'       : 'warn',
    'jest/no-conditional-expect'        : 'warn',
    'jest/no-deprecated-functions'      : 'warn',
    'jest/no-disabled-tests'            : 'warn',
    'jest/no-done-callback'             : 'off',
    'jest/no-duplicate-hooks'           : 'warn',
    'jest/no-export'                    : 'off',
    'jest/no-focused-tests'             : 'warn',
    'jest/no-hooks'                     : 'warn',
    'jest/no-identical-title'           : 'warn',
    'jest/no-if'                        : 'off',
    'jest/no-interpolation-in-snapshots': 'warn',
    'jest/no-jasmine-globals'           : 'warn',
    'jest/no-jest-import'               : 'warn',
    'jest/no-large-snapshots'           : 'warn',
    'jest/no-mocks-import'              : 'off',
    'jest/no-restricted-matchers'       : 'warn',
    'jest/no-standalone-expect'         : 'warn',
    'jest/no-test-prefixes'             : 'warn',
    'jest/no-test-return-statement'     : 'warn',
    'jest/prefer-called-with'           : 'warn',
    'jest/prefer-expect-assertions'     : 'off',
    'jest/prefer-expect-resolves'       : 'warn',
    'jest/prefer-hooks-on-top'          : 'warn',
    'jest/prefer-lowercase-title'       : 'warn',
    'jest/prefer-spy-on'                : 'warn',
    'jest/prefer-strict-equal'          : 'warn',
    'jest/prefer-to-be'                 : 'warn',
    'jest/prefer-to-contain'            : 'warn',
    'jest/prefer-to-have-length'        : 'warn',
    'jest/prefer-todo'                  : 'warn',
    'jest/require-hook'                 : 'error',
    'jest/require-to-throw-message'     : 'error',
    'jest/require-top-level-describe'   : 'error',
    'jest/unbound-method'               : 'error',
    'jest/valid-describe-callback'      : 'error',
    'jest/valid-expect'                 : 'warn',
    'jest/valid-expect-in-promise'      : 'warn',
    'jest/valid-title'                  : 'error',
  },
};
