module.exports = {
  'plugins': [
    'jest',
  ],
  'env': {
    'jest': true,
  },
  'extends': [
    'plugin:jest/recommended',
  ],
  'rules': {
    'jest/consistent-test-it'           : 'warn',
    'jest/expect-expect'                : 'warn',
    'jest/lowercase-name'               : 'warn',
    'jest/no-alias-methods'             : 'warn',
    'jest/no-commented-out-tests'       : 'warn',
    'jest/no-conditional-expect'        : 'warn',
    'jest/no-deprecated-functions'      : 'warn',
    'jest/no-disabled-tests'            : 'warn',
    'jest/no-done-callback'             : 'warn',
    'jest/no-duplicate-hooks'           : 'warn',
    'jest/no-export'                    : 'warn',
    'jest/no-focused-tests'             : 'warn',
    'jest/no-hooks'                     : 'off',
    'jest/no-identical-title'           : 'warn',
    'jest/no-if'                        : 'warn',
    'jest/no-interpolation-in-snapshots': 'warn',
    'jest/no-jasmine-globals'           : 'warn',
    'jest/no-jest-import'               : 'warn',
    'jest/no-large-snapshots'           : 'warn',
    'jest/no-mocks-import'              : 'warn',
    'jest/no-restricted-matchers'       : [
      'error',
      {
        'resolves'                          : 'Use `expect(await promise)` instead.',
        'toBeFalsy'                         : 'Avoid `toBeFalsy`',
        'toBeTruthy'                        : 'Avoid `toBeTruthy`',
        'toMatchInlineSnapshot'             : 'Use `toMatchSnapshot()` instead',
        'toThrowErrorMatchingInlineSnapshot': 'Use `toThrowErrorMatchingSnapshot()` instead',
      },
    ],
    'jest/no-standalone-expect'      : 'warn',
    'jest/no-test-prefixes'          : 'warn',
    'jest/no-test-return-statement'  : 'warn',
    'jest/no-try-expect'             : 'warn',
    'jest/prefer-called-with'        : 'warn',
    'jest/prefer-expect-assertions'  : 'off',
    'jest/prefer-hooks-on-top'       : 'warn',
    'jest/prefer-spy-on'             : 'warn',
    'jest/prefer-strict-equal'       : 'warn',
    'jest/prefer-to-be-null'         : 'warn',
    'jest/prefer-to-be-undefined'    : 'warn',
    'jest/prefer-to-contain'         : 'warn',
    'jest/prefer-to-have-length'     : 'warn',
    'jest/prefer-todo'               : 'warn',
    'jest/require-to-throw-message'  : 'warn',
    'jest/require-top-level-describe': 'warn',
    'jest/unbound-method'            : 'warn',
    'jest/valid-describe'            : 'warn',
    'jest/valid-expect'              : 'warn',
    'jest/valid-expect-in-promise'   : 'warn',
    'jest/valid-title'               : 'warn',
  },
};
