name: Node.js Package

on:
  push:
    branches: 
      - master
    paths: 
      - src

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Create release
        uses: TriPSs/conventional-changelog-action@v1.2.0
        with:
          github-token: ${{ secrets.github_token }}
          git-message: 'chore(release): {version}'
          changelog-release-count: 0
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
