name: Create release and publish to NPM

on:
  pull_request: ~
  push:
    branches:
      - main
    paths:
      - src/**/*
      - package.json
      - package-lock.json

  workflow_dispatch: ~

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: myparcelnl/actions/yarn-install@v1

      - name: Build package
        run: npm run build

      - name: Run tests
        run: npm test

      - uses: myparcelnl/actions/update-coverage@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: myparcelnl/actions/semantic-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
