name: Create release and publish to NPM

on:
  pull_request: ~
  push:
    branches:
      - main
    paths:
      - src/**/*
      - package.json
      - package-lock.json

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci

      - name: Build package
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Update coverage
        uses: codecov/codecov-action@v1

      - name: Run semantic release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
