name: Create release and publish to NPM

on:
  pull_request: ~
  push:
    branches:
      - master
    paths:
      - src/*
      - package.json
      - package-lock.json

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci

      - name: Build package
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Update coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run semantic release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: brpaz/action-semantic-release@v1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
